image: debian:bookworm
build:
  environment:
    name: $CI_COMMIT_REF_NAME
  script:
    - apt-get update
    - apt-get -y install python3-venv
    - cd /builds/ai/bots/psychedelic-bot
    - python3 -m venv venv
    - . venv/bin/activate
    - git clone https://github.com/Vaelor/python-mattermost-driver
    - cd python-mattermost-driver
    - python3 setup.py install
    - cd ..
    - pip install -r requirements.txt
    - python3 app.py
  when: manual