image: python:3.10.6-slim-bullseye

stages:
  - deploy

deploy:
  environment:
    name: $CI_COMMIT_BRANCH
  interruptible: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  script:
    - ssh -oStrictHostKeyChecking=no psychedelic-bot@ai.psychedelic.fi $CI_COMMIT_BRANCH
  stage: deploy
