image: debian:bookworm-slim

stages:
  - deploy

deploy:
  environment:
    name: $CI_COMMIT_BRANCH
  interruptible: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  script:
    - apt-get update
    - apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_DEPLOY_KEY"
    - ssh-add "$SSH_DEPLOY_KEY"
    - ssh -oStrictHostKeyChecking=no psychedelic-bot@ai.psychedelic.fi $CI_COMMIT_BRANCH
  stage: deploy
