image: python:3.10.6-slim-bullseye

stages:
- build
- test
- deploy

venv:
  artifacts:
    paths:
    - venv/
    when: on_success
  interruptible: true
  script:
    - apt-get update
    - apt-get -y install g++ gcc python3-dev python3-wheel
    - python -um venv venv
    - . venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  stage: build

pylint:
  interruptible: true
  needs:
  - venv
  script:
  - . venv/bin/activate
  - pylint *.py
  stage: test

update:
  before_script:
  - 'command -v ssh-agent >/dev/null || (apt-get update -y && apt-get install openssh-client -y)'
  - eval $(ssh-agent -s)
  - chmod 400 "$SSH_DEPLOY_KEY"
  - ssh-add "$SSH_DEPLOY_KEY"
  - mkdir -pm 700 ~/.ssh
  environment:
    name: $CI_COMMIT_BRANCH
  interruptible: true
  needs:
  - venv
  - pylint
  rules:
  - if: $CI_COMMIT_TAG
    when: never
  - when: on_success
  script:
  - ssh -oStrictHostKeyChecking=no psychedelic-bot@ai.psychedelic.fi $CI_COMMIT_BRANCH
  stage: deploy
