image: python:3.10
deploy:
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_NAME
  needs:
    - build
  script:
    - cd /builds/ai/bots/psychedelic-bot
    - pip install -r requirements.txt
    - python app.py
  when: manual