stages:
  - test
  - deploy

test:
  image: python:3.9
  interruptible: true
  script:
    - cd /builds/ai/bots/psychedelic-bot
    - pip install openai mattermostdriver pylint
    - pylint app.py

deploy:
  image: gitlab.psychedelic.fi:5050/ai/bots/psychedelic-bot:latest
  interruptible: true
  environment:
    name: $CI_COMMIT_BRANCH
  script:
    - python3 app.py