image: python:3.10
cache:
  paths:
    - venv
stages:
  - build
  - deploy
create_venv:
  stage: build
  script:
    - cd /builds/ai/bots/psychedelic-bot
    - python -m venv venv
    - . venv/bin/activate
    - pip install -r requirements.txt
  artifacts:
    paths:
      - venv
run_service:
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_NAME
  needs:
    - create_venv
  script:
    - . venv/bin/activate
    - python app.py
  when: manual
