image: python:3.10.6-slim-bullseye

stages:
  - deploy

deploy:
  environment:
    name: $CI_COMMIT_BRANCH
  interruptible: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  script:
    - apt-get update
    - apt-get install g++ gcc openssh-client python3-dev python3-wheel -y
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_DEPLOY_KEY"
    - ssh-add "$SSH_DEPLOY_KEY"
    - mkdir -pm 700 ~/.ssh
    - python -um venv venv
    - . venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pylint *.py
    - ssh -oStrictHostKeyChecking=no psychedelic-bot@ai.psychedelic.fi $CI_COMMIT_BRANCH
  stage: deploy
