stages:
- test
- deploy

test:
  image: python:3.9
  interruptible: true
  script:
  - cd /builds/ai/bots/psychedelic-bot
  - pip install openai mattermostdriver pylint
  - pylint app.py

deploy:
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - chmod 400 "$SSH_DEPLOY_KEY"
  - ssh-add "$SSH_DEPLOY_KEY"
  - mkdir -pm 700 ~/.ssh
  environment:
    name: $CI_COMMIT_BRANCH
  interruptible: true
  needs:
  - test
  script:
  - scp -oStrictHostKeyChecking=no -pr $DEPLOY_ENVIRONMENT psychedelic-bot@ai.psychedelic.fi:$MATTERMOST_BOTNAME.env
  - ssh -oStrictHostKeyChecking=no psychedelic-bot@ai.psychedelic.fi $MATTERMOST_BOTNAME