image: python:3.10
build:
  environment:
    name: $CI_COMMIT_REF_NAME
  script:
    - cd /builds/ai/bots/psychedelic-bot
    - python -m venv venv
    - . venv/bin/activate
    - git clone https://github.com/Vaelor/python-mattermost-driver
    - cd python-mattermost-driver
    - python setup.py install
    - cd ..
    - pip install -r requirements.txt
    - python app.py
  when: manual