deploy:
  environment:
    name: "$CI_COMMIT_BRANCH"
  interruptible: true
  rules:
    - if: "$CI_COMMIT_TAG"
      when: never
    - when: on_success
  script:
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_DEPLOY_KEY"
    - ssh-add "$SSH_DEPLOY_KEY"
    - ssh -oStrictHostKeyChecking=no psychedelic-bot@ai.psychedelic.fi $CI_COMMIT_BRANCH
  stage: deploy
  tags:
    - shell
include:
  - template: Security/Secret-Detection.gitlab-ci.yml