stages:
  - test
  - deploy
test:
  image: python:3.9
  interruptible: true
  script:
    - cd /builds/ai/bots/psychedelic-bot
    - pip install openai mattermostdriver pylint
    - pylint app.py
deploy:
  image: debian:bullseye
  interruptible: true
  environment:
    name: $CI_COMMIT_REF_NAME
  script:
    - apt-get update
    - apt-get -y install build-essential git python3-dev python3-venv python3-wheel
    - cd /builds/ai/bots/psychedelic-bot
    - python3 -m venv venv
    - . venv/bin/activate
    - git clone https://github.com/Vaelor/python-mattermost-driver
    - cd python-mattermost-driver
    - pip install -r requirements.txt
    - python3 setup.py install
    - cd ..
    - pip install openai
    - python3 app.py