deploy:
  before_script:
  - 'command -v ssh-agent >/dev/null || (apt-get update -y && apt-get install openssh-client -y)'
  - eval $(ssh-agent -s)
  - chmod 400 "$SSH_DEPLOY_KEY"
  - ssh-add "$SSH_DEPLOY_KEY"
  - mkdir -pm 700 ~/.ssh
  environment:
    name: $CI_COMMIT_BRANCH
  interruptible: true
  rules:
  - if: $CI_COMMIT_TAG
    when: never
  - when: on_success
  script:
  - ssh -oStrictHostKeyChecking=no psychedelic-bot@ai.psychedelic.fi $CI_COMMIT_BRANCH
  stage: deploy
